Repository COS301-SE-2022/Vote-Vault, pull requests merged in 2022-06, with the labels that each got.

#79 Merge feature-Website to develop to delete feature-Website
  Frontend/Website/Vote-Vault-Website/angular.json
  Frontend/Website/Vote-Vault-Website/package-lock.json
  Frontend/Website/Vote-Vault-Website/package.json
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/app.component.html
  Frontend/Website/Vote-Vault-Website/src/app/app.module.ts
  Frontend/Website/Vote-Vault-Website/src/polyfills.ts
Labels: bug, scope:ui, priority:medium

#82 Merging feature-website with develop
  Frontend/Voting App/VoteVault/angular.json
  Frontend/Voting App/VoteVault/package-lock.json
  Frontend/Voting App/VoteVault/package.json
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.module.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.html
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.scss
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.ts
  Frontend/Voting App/VoteVault/src/app/app-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/app.module.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.html
  Frontend/Voting App/VoteVault/src/app/login/login.page.scss
  Frontend/Voting App/VoteVault/src/app/login/login.page.ts
  Frontend/Voting App/VoteVault/src/environments/environment.ts
  Frontend/Voting App/VoteVault/tsconfig.json
  Frontend/Website/Vote-Vault-Website/package-lock.json
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/app-routing.module.ts
  Frontend/Website/Vote-Vault-Website/src/app/app.component.html
  Frontend/Website/Vote-Vault-Website/src/app/app.module.ts
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/assets/images/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/assets/images/howto-register.png
  Frontend/Website/Vote-Vault-Website/src/assets/vote.ico
  Frontend/Website/Vote-Vault-Website/src/index.html
  Frontend/Website/Vote-Vault-Website/src/styles.css
  Frontend/Website/Vote-Vault-Website/tsconfig.json
  README.md
  package-lock.json
  package.json
Labels: scope:client

#101 Merge into develop
  .github/workflows/frontend-test.yml
  Frontend/Voting App/VoteVault/karma.conf.js
  Frontend/Voting App/VoteVault/package-lock.json
  Frontend/Voting App/VoteVault/package.json
  Frontend/Voting App/VoteVault/src/app/login/login.page.spec.ts
  Frontend/Website/Vote-Vault-Website/karma.conf.js
  Frontend/Website/Vote-Vault-Website/package-lock.json
  Frontend/Website/Vote-Vault-Website/package.json
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/app.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/home-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/assets/images/appPlaceholder.jpg
  Frontend/Website/Vote-Vault-Website/src/assets/logoipsum-logo-27.svg
  Frontend/Website/Vote-Vault-Website/src/index.html
  Frontend/Website/Vote-Vault-Website/src/styles.css
Labels: priority:high, fix

#109 Feature mobile app
  Frontend/Voting App/VoteVault/package-lock.json
  Frontend/Voting App/VoteVault/package.json
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.module.ts
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.html
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.scss
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.html
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.scss
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.ts
  Frontend/Voting App/VoteVault/src/app/app-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/app.component.html
  Frontend/Voting App/VoteVault/src/app/app.module.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.html
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.ts
  Frontend/Voting App/VoteVault/src/app/data.service.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.html
  Frontend/Voting App/VoteVault/src/app/login/login.page.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
  Frontend/Voting App/VoteVault/src/app/register/register.page.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.module.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.html
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.scss
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.ts
Labels: scope:client, priority:medium

#127 Feature website
  Frontend/Voting App/VoteVault/karma.conf.js
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.html
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.scss
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.ts
  Frontend/Voting App/VoteVault/src/app/app.component.spec.ts
  Frontend/Voting App/VoteVault/src/app/app.module.ts
  Frontend/Voting App/VoteVault/src/app/data.service.spec.ts
  Frontend/Voting App/VoteVault/src/app/data.service.ts
  Frontend/Voting App/VoteVault/src/app/register/register.module.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.html
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.scss
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.ts
  Frontend/Voting App/VoteVault/src/app/voter-registration/voter-registration.page.spec.ts
  Frontend/Website/Vote-Vault-Website/karma.conf.js
  Frontend/Website/Vote-Vault-Website/package.json
  Frontend/Website/Vote-Vault-Website/tsconfig.json
Labels: scope:ui, priority:low, scope:test, fix

#140 Feature website
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/history-page/history-page.component.ts
Labels: priority:low, scope:test, fix

#143 Fixed random app tests failing
  Frontend/Voting App/VoteVault/karma.conf.js
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/app.component.spec.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/data.service.spec.ts
  Frontend/Voting App/VoteVault/src/app/folder/folder.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/voter-registration/voter-registration.page.spec.ts
Labels: scope:test, fix

#144 Develop
  Frontend/Voting App/VoteVault/karma.conf.js
  Frontend/Voting App/VoteVault/src/app/admin-dashboard/admin-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/admin-login/admin-login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/app.component.spec.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/data.service.spec.ts
  Frontend/Voting App/VoteVault/src/app/folder/folder.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.ts
  Frontend/Voting App/VoteVault/src/app/voter-dashboard/voter-dashboard.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/voter-registration/voter-registration.page.spec.ts
Labels: bug, scope:test, fix
