Repository COS301-SE-2022/Vote-Vault, pull requests merged in 2022-05, with the labels that each got.

#14 💬 (README) Added new links
  README.md
Labels: documentation

#15 🚚 (File Structure) Added a file structure
  Backend/API/something.html
  Backend/Blockchain/something.html
  Frontend/Voting App/VoteVault/.browserslistrc
  Frontend/Voting App/VoteVault/.editorconfig
  Frontend/Voting App/VoteVault/.eslintrc.json
  Frontend/Voting App/VoteVault/.gitignore
  Frontend/Voting App/VoteVault/angular.json
  Frontend/Voting App/VoteVault/capacitor.config.ts
  Frontend/Voting App/VoteVault/e2e/protractor.conf.js
  Frontend/Voting App/VoteVault/e2e/src/app.e2e-spec.ts
  Frontend/Voting App/VoteVault/e2e/src/app.po.ts
  Frontend/Voting App/VoteVault/e2e/tsconfig.json
  Frontend/Voting App/VoteVault/ionic.config.json
  Frontend/Voting App/VoteVault/karma.conf.js
  Frontend/Voting App/VoteVault/package-lock.json
  Frontend/Voting App/VoteVault/package.json
  Frontend/Voting App/VoteVault/src/app/app-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/app.component.html
  Frontend/Voting App/VoteVault/src/app/app.component.scss
  Frontend/Voting App/VoteVault/src/app/app.component.spec.ts
  Frontend/Voting App/VoteVault/src/app/app.component.ts
  Frontend/Voting App/VoteVault/src/app/app.module.ts
  Frontend/Voting App/VoteVault/src/app/folder/folder-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/folder/folder.module.ts
  Frontend/Voting App/VoteVault/src/app/folder/folder.page.html
  Frontend/Voting App/VoteVault/src/app/folder/folder.page.scss
  Frontend/Voting App/VoteVault/src/app/folder/folder.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/folder/folder.page.ts
  Frontend/Voting App/VoteVault/src/app/login/login-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/login/login.module.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.html
  Frontend/Voting App/VoteVault/src/app/login/login.page.scss
  Frontend/Voting App/VoteVault/src/app/login/login.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.ts
  Frontend/Voting App/VoteVault/src/app/register/register-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/register/register.module.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
  Frontend/Voting App/VoteVault/src/app/register/register.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.ts
  Frontend/Voting App/VoteVault/src/assets/icon/favicon.png
  Frontend/Voting App/VoteVault/src/assets/shapes.svg
  Frontend/Voting App/VoteVault/src/environments/environment.prod.ts
  Frontend/Voting App/VoteVault/src/environments/environment.ts
  Frontend/Voting App/VoteVault/src/global.scss
  Frontend/Voting App/VoteVault/src/index.html
  Frontend/Voting App/VoteVault/src/main.ts
  Frontend/Voting App/VoteVault/src/polyfills.ts
  Frontend/Voting App/VoteVault/src/test.ts
  Frontend/Voting App/VoteVault/src/theme/variables.scss
  Frontend/Voting App/VoteVault/src/zone-flags.ts
  Frontend/Voting App/VoteVault/tsconfig.app.json
  Frontend/Voting App/VoteVault/tsconfig.json
  Frontend/Voting App/VoteVault/tsconfig.spec.json
  Frontend/Website/something.html
  README.md
Labels: help wanted, priority:medium

#22 ✨ (UI) : Generate-ballot and ballot page
  Frontend/Voting App/VoteVault/src/app/app-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.module.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.html
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.ts
  Frontend/Voting App/VoteVault/src/app/data.service.spec.ts
  Frontend/Voting App/VoteVault/src/app/data.service.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.module.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.spec.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.ts
  Frontend/Voting App/VoteVault/src/app/login/login.page.scss
Labels: scope:ui, priority:medium

#25 📁 (Website) Generated website files
  Frontend/Website/Vote-Vault-Website/.browserslistrc
  Frontend/Website/Vote-Vault-Website/.editorconfig
  Frontend/Website/Vote-Vault-Website/.gitignore
  Frontend/Website/Vote-Vault-Website/.vscode/extensions.json
  Frontend/Website/Vote-Vault-Website/.vscode/launch.json
  Frontend/Website/Vote-Vault-Website/.vscode/tasks.json
  Frontend/Website/Vote-Vault-Website/README.md
  Frontend/Website/Vote-Vault-Website/angular.json
  Frontend/Website/Vote-Vault-Website/karma.conf.js
  Frontend/Website/Vote-Vault-Website/package-lock.json
  Frontend/Website/Vote-Vault-Website/package.json
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/app-routing.module.ts
  Frontend/Website/Vote-Vault-Website/src/app/app.component.css
  Frontend/Website/Vote-Vault-Website/src/app/app.component.html
  Frontend/Website/Vote-Vault-Website/src/app/app.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/app.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/app.module.ts
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/assets/.gitkeep
  Frontend/Website/Vote-Vault-Website/src/environments/environment.prod.ts
  Frontend/Website/Vote-Vault-Website/src/environments/environment.ts
  Frontend/Website/Vote-Vault-Website/src/favicon.ico
  Frontend/Website/Vote-Vault-Website/src/index.html
  Frontend/Website/Vote-Vault-Website/src/main.ts
  Frontend/Website/Vote-Vault-Website/src/polyfills.ts
  Frontend/Website/Vote-Vault-Website/src/styles.css
  Frontend/Website/Vote-Vault-Website/src/test.ts
  Frontend/Website/Vote-Vault-Website/tsconfig.app.json
  Frontend/Website/Vote-Vault-Website/tsconfig.json
  Frontend/Website/Vote-Vault-Website/tsconfig.spec.json
  Frontend/Website/index.html
Labels: priority:medium

#27 ✨ Adds Card Component for voter registration
  .gitignore
  Frontend/Voting App/VoteVault/capacitor.config.json
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
Labels: scope:ui, priority:low

#31 🩹 (UI) Edits Card Component to have relevant text fields
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
Labels: scope:ui, priority:low

#36 🩹 Fixes Card of Voter Registration page
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
Labels: scope:ui, priority:low

#37 🩹 Fixes desktop Card width
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
Labels: scope:ui, priority:low

#38 🔥 Removes useless class declaration
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
Labels: scope:ui, priority:low

#41 ✨ (UI) : Voter form generation
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.html
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.ts
  Frontend/Voting App/VoteVault/src/app/data.service.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.ts
Labels: enhancement, scope:ui, priority:medium

#45 ✨ (UI) : Added generate-ballot and ballot pages
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.html
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
Labels: enhancement, scope:ui, priority:medium

#47 ✨ Feature mobile app
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.html
  Frontend/Voting App/VoteVault/src/app/ballot/ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
Labels: scope:ui, priority:medium

#48 ✨ Adds some functionality to Voter Registration page
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.ts
Labels: enhancement, scope:ui, priority:high

#50 ✨ Feature mobile app
  Frontend/Voting App/VoteVault/src/app/app.component.html
  Frontend/Voting App/VoteVault/src/app/app.component.scss
  Frontend/Voting App/VoteVault/src/app/app.component.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
  Frontend/Voting App/VoteVault/src/app/register/register.page.ts
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.html
Labels: enhancement, scope:ui, priority:medium

#52 🔀 Merging Develop with Main
  Frontend/Voting App/VoteVault/src/app/app.component.html
  Frontend/Voting App/VoteVault/src/app/app.component.scss
  Frontend/Voting App/VoteVault/src/app/app.component.ts
Labels: scope:ui, priority:medium

#53 💄(UI) : Changes to generate Ballot
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.scss
Labels: enhancement, scope:ui

#54 🔀 merging feature-Mobile-App into develop
  Frontend/Voting App/VoteVault/src/app/app-routing.module.ts
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.html
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.scss
  Frontend/Voting App/VoteVault/src/app/generate-ballot/generate-ballot.page.ts
Labels: scope:ui, priority:low

#57 🔀 Updated margin of submit button
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
Labels: scope:ui, priority:low

#58 Bevanslabbert patch 1
  .github/workflows/github-actions-demo
Labels: enhancement, scope:test

#62 :sparkles: Updated app icons
  Frontend/Voting App/VoteVault/src/app/app.component.html
  Frontend/Voting App/VoteVault/src/app/app.component.ts
  Frontend/Voting App/VoteVault/src/app/register/register.page.html
  Frontend/Voting App/VoteVault/src/app/register/register.page.scss
Labels: scope:ui, priority:low

#67 Feature website
  Frontend/Website/Vote-Vault-Website/package-lock.json
  Frontend/Website/Vote-Vault-Website/package.json
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.spec.ts
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/analytics-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/analytics-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/app.component.ts
  Frontend/Website/Vote-Vault-Website/src/app/app.module.ts
  Frontend/Website/Vote-Vault-Website/src/app/home-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/home-page/home-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/howto-page/howto-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/fortuna.jpeg
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.html
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.ts
  Frontend/Website/Vote-Vault-Website/src/styles.css
Labels: help wanted, scope:ui, scope:client, priority:medium

#69 Feature website
  .github/workflows/frontend-test.yml
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.css
  Frontend/Website/Vote-Vault-Website/src/app/results-page/results-page.component.html
  Frontend/Website/Vote-Vault-Website/src/index.html
  Frontend/Website/Vote-Vault-Website/src/vote.ico
Labels: priority:high
